Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-11, with the labels that each got.

#137 Update CI to 6.0.22
  .circleci/config.yml
  CHANGELOG.md
Labels: 0 diff structural, 0 diff trivial

#139 sdrabenh/feature/plotupdates_20201125
  CHANGELOG.md
  GEOS_Util/plots/grads_util/closeness.gs
  GEOS_Util/plots/grads_util/label
  GEOS_Util/plots/grads_util/makezdif.gs
  GEOS_Util/plots/grads_util/parea
  GEOS_Util/plots/grads_util/plot.rc
  GEOS_Util/plots/grads_util/zdiff.template
  GEOS_Util/plots/quickstat
  GEOS_Util/plots/res/zonal.gs
  GEOS_Util/plots/zcmp/zcloseplt
  GEOS_Util/plots/zonal.f
  GEOS_Util/post/alias.F
  GEOS_Util/post/alias.com
  GEOS_Util/post/time_ave.rc
Labels: 0 diff

#136 add dependency to turn on BUILD_SHARED_LIBS
  CHANGELOG.md
  GMAO_transf/CMakeLists.txt
  GMAO_transf/m_massadj.F90
Labels: 0 diff

#140 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#141 Move to CircleCI Medium Resource Class
  .circleci/config.yml
Labels: 0 diff trivial, Skip Changelog
