Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-04, with the labels that each got.

#69 Shared module for lightning flash rate computation
  GEOS_Shared/CMakeLists.txt
  GEOS_Shared/Lightning_mod.F90
  GEOS_Shared/lightning_toolbox_mod.F90
Labels: 0 diff

#89 Fixes #88. Intel MPI on SLES 12/SLURM 19 is good
  GMAO_etc/esma_mpirun
Labels: 0 diff, bugfix

#87 Fixes #86 - duplicate symbol for flat2hdf.x
  CHANGELOG.md
  GEOS_Util/post/CMakeLists.txt
Labels: 0 diff structural, bugfix

#92 Fixes #85. Compile convert_aerosols.x as r8
  GEOS_Util/post/CMakeLists.txt
Labels: 0 diff structural, Non 0-diff, bugfix

#90 The regrid.pl script was updated for SLES-12
  GEOS_Util/post/regrid.pl
Labels: 0 diff, bugfix
