Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-07, with the labels that each got.

#105 Fixes #104. Remove extraneous comma
  GEOS_Shared/lightning_toolbox_mod.F90
Labels: 0 diff, bugfix

#106 Fixes GCC 10 Release Build
  GMAO_hermes/CMakeLists.txt
  GMAO_transf/CMakeLists.txt
Labels: 0 diff, 0 diff structural

#107 Use r4i4 ncep_sp in gmao_transf
  GMAO_transf/CMakeLists.txt
Labels: 0 diff, Non 0-diff, bug, bugfix

#108 Plot updates by Takacs on 2020-07-21
  GEOS_Util/plots/grads_util/plot.rc
  GEOS_Util/plots/res/res_2.gs
  GEOS_Util/plots/res/res_3.gs
  GEOS_Util/plots/tseries/rad_3
  GEOS_Util/plots/tseries/rad_4
  GEOS_Util/plots/zcmp/progz
Labels: 0 diff

#109 Edit Open MPI flags
  GMAO_etc/esma_mpirun
Labels: 0 diff
