Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-03, with the labels that each got.

#79 Plot updates from Jason-3_6_p1
  GEOS_Util/plots/fcst/pltcorcmp.gs
  GEOS_Util/plots/grads_util/plot.rc
  GEOS_Util/plots/hcmp/hcmp2
  GEOS_Util/plots/hcmp/hplt
  GEOS_Util/plots/landscape.script
  GEOS_Util/plots/portrait.script
  GEOS_Util/plots/quickstat
  GEOS_Util/plots/tseries/aeromont
  GEOS_Util/plots/tseries/aeroplot
  GEOS_Util/plots/tseries/aerosols
  GEOS_Util/plots/zcmp/progz
  GEOS_Util/plots/zcmp/zcloseplt
  GEOS_Util/plots/zcmp/zplt
Labels: 0 diff, enhancement

#81 Feature/wjiang/#149 add write eta
  CMakeLists.txt
  GMAO_hermes/CMakeLists.txt
  GMAO_hermes/m_topo_remap.F90
  GMAO_hermes/shared_topo_remap.F90
  GMAO_hermes/unused_dummy.H
  GMAO_hermes/write_eta.F90
Labels: 0 diff

#80 Add model option to quickstat
  GEOS_Util/plots/quickstat
Labels: 0 diff structural

#82 add option to build HERMES_LIGHT
  CMakeLists.txt
Labels: 0 diff, 0 diff structural

#83 J36p2_updates
  GEOS_Util/post/gcmpost.script
Labels: 0 diff

#84 Fixes for CMake using F2Py and LaTeX
  GMAO_gfio/CMakeLists.txt
Labels: 0 diff structural
