Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-10, with the labels that each got.

#125 Modify plots to display new constraint diagnostics
  CHANGELOG.md
  GEOS_Util/plots/grads_util/makezf
  GEOS_Util/plots/grads_util/plot.rc
  GEOS_Util/plots/landscape.script
  GEOS_Util/plots/portrait.script
  GEOS_Util/plots/res/res_2.gs
  GEOS_Util/plots/res/res_3.gs
  GEOS_Util/plots/zcmp/zplt
Labels: 0 diff

#126 Feature/san akel/aoil v2.0 dev
  CHANGELOG.md
  GEOS_Shared/atmOceanIntLayer.F90
Labels: 0 diff structural

#130 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial, documentation

#124 Regrid_forcing for MAPL2.2
  CHANGELOG.md
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/regrid_forcing.F90
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/regrid_forcing_esmf.F90
Labels: 0 diff, bugfix

#129 Fixes #128. Refactor PBS_NODEFILE code in post
  CHANGELOG.md
  GEOS_Util/post/gcmclim.script
  GEOS_Util/post/gcmpost.script
  GEOS_Util/post/gcmpost_CPLFCSTfull.script
  GEOS_Util/post/gcmpost_CPLFCSTpart.script
Labels: 0 diff

#131 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#133 Add Docker authentication for pulls
  .circleci/config.yml
  CHANGELOG.md
Labels: 0 diff structural

#132 Add logger for NaN detection in QSAT calls
  CHANGELOG.md
  GEOS_Shared/GEOS_Utilities.F90
Labels: 0 diff trivial, enhancement

#134 Edits to make plots/configure portable
  CHANGELOG.md
  GEOS_Util/plots/CMakeLists.txt
  GEOS_Util/plots/configure
Labels: 0 diff
