Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-12, with the labels that each got.

#142 Use CONFIGURE_DEPENDS with GLOB
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
  GEOS_Util/coupled_diagnostics/CMakeLists.txt
  GEOS_Util/plots/CMakeLists.txt
  GEOS_Util/post/CMakeLists.txt
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
  GMAO_etc/CMakeLists.txt
  GMAO_hermes/CMakeLists.txt
Labels: 0 diff, 0 diff structural

#143 Changes needed to allow use of aggressive flags with GEOS
  CHANGELOG.md
  GMAO_stoch/CMakeLists.txt
  GMAO_stoch/mod_four.F90
  GMAO_transf/CMakeLists.txt
Labels: 0 diff, 0 diff structural

#144 Update CHANGELOG.md [skip ci]
  CHANGELOG.md
Labels: 0 diff trivial

#148 Force 0 to 1 range if needed in regrid_forcing_esmf.x
  CHANGELOG.md
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/regrid_forcing_esmf.F90
Labels: 0 diff, bugfix

#149 Update changelog enforcer [skip ci]
  .github/workflows/changelog-enforcer.yml
Labels: 0 diff trivial, enhancement
