Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-09, with the labels that each got.

#118 Update the changelog to present day
  .github/CODEOWNERS
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
Labels: 0 diff structural, 0 diff trivial

#117 Feature/san akel/simplify aoil
  CHANGELOG.md
  GEOS_Shared/CMakeLists.txt
  GEOS_Shared/atmOceanIntLayer.F90
Labels: 0 diff structural, enhancement

#119 Update CircleCI image for 6.0.16
  .circleci/config.yml
  CHANGELOG.md
Labels: 0 diff, 0 diff structural, 0 diff trivial

#115 Update GEOS_Utilities to match ADAS
  CHANGELOG.md
  GEOS_Shared/GEOS_Utilities.F90
Labels: Non 0-diff

#123 Move back to using int() not nint(): Bug in Table Evaluation
  CHANGELOG.md
  GEOS_Shared/GEOS_Utilities.F90
Labels: Non 0-diff, bugfix
