Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2020-08, with the labels that each got.

#110 Fixes to allow Intel 19.1.2 to use CICE
  LANL_Shared/LANL_cice/source/ice_grid.F90
Labels: 0 diff

#113 Add CircleCI build for GEOS_Shared
  .circleci/config.yml
Labels: 0 diff structural

#114 Assume Open MPI as a default mpi stack
  GMAO_etc/esma_mpirun
Labels: 0 diff

#112 Feature/san akel/for data lake
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/README_lake
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/gen_input.csh
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/lake_data_EIGTHdeg.F90
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/plot_bcs.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/proc_singleDay.csh
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/read_bin.f90
Labels: 0 diff trivial
