Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2021-01, with the labels that each got.

#145 Update flags for zonal.f to match CVS; fix zonal.gs
  CHANGELOG.md
  GEOS_Util/plots/CMakeLists.txt
  GEOS_Util/plots/res/zonal.gs
Labels: 0 diff

#150 Update CI image to 6.0.27.
  .circleci/config.yml
Labels: 0 diff trivial

#146 Add partition option for regrid
  CHANGELOG.md
  GEOS_Util/post/regrid.pl
Labels: 0 diff

#151 [skip ci] Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#153 Plot and stat updates from ltakacs on 2021-01-15
  CHANGELOG.md
  GEOS_Util/plots/grads_util/corcmpz_plot.gs
  GEOS_Util/plots/grads_util/genplt.gs
  GEOS_Util/plots/grads_util/plot.rc
  GEOS_Util/plots/grads_util/rmscmpz_plot.gs
  GEOS_Util/plots/movestat
  GEOS_Util/plots/quickplot
  GEOS_Util/plots/quickstat
  GEOS_Util/plots/res/zonal.gs
  GEOS_Util/plots/tseries/ps_1
  GEOS_Util/plots/zcmp/progz
  GEOS_Util/post/stats.F90
Labels: 0 diff

#152 Fix the zonal.f make flags
  CHANGELOG.md
  GEOS_Util/plots/CMakeLists.txt
Labels: 0 diff, bugfix
