Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2021-12, with the labels that each got.

#233 The idcheck.pl script was updated for changes in SemperPy
  CHANGELOG.md
  GMAO_etc/idcheck.pl
Labels: 0 diff trivial

#222 Update regrid.pl for Ocean Model Questions
  .circleci/config.yml
  CHANGELOG.md
  GEOS_Util/post/CMakeLists.txt
  GEOS_Util/post/regrid.pl
Labels: enhancement, 0 diff

#234 [skip ci] Prepare to tag v1.4.12
  CHANGELOG.md
Labels: 0 diff trivial

#235 3CH and GOCART-2G Plot Updates from L. Takacs
  CHANGELOG.md
  GEOS_Util/plots/chckhist.new
  GEOS_Util/plots/grads_util/closeness.gs
  GEOS_Util/plots/grads_util/corcmp_plot.gs
  GEOS_Util/plots/grads_util/corcmpz_plot.gs
  GEOS_Util/plots/grads_util/genplot_2G.gs
  GEOS_Util/plots/grads_util/genpltz.gs
  GEOS_Util/plots/grads_util/getvar_2G.gs
  GEOS_Util/plots/grads_util/getvarz.gs
  GEOS_Util/plots/grads_util/lines
  GEOS_Util/plots/grads_util/make_ts.gs
  GEOS_Util/plots/grads_util/makezdif.gs
  GEOS_Util/plots/grads_util/makezf
  GEOS_Util/plots/grads_util/makplot.gs
  GEOS_Util/plots/grads_util/parea
  GEOS_Util/plots/grads_util/rmscmp_plot.gs
  GEOS_Util/plots/grads_util/rmscmpz_plot.gs
  GEOS_Util/plots/grads_util/vpage
  GEOS_Util/plots/grads_util/writegrads.gs
  GEOS_Util/plots/portrait.script
  GEOS_Util/plots/quickstat
  GEOS_Util/plots/res/res_2.gs
  GEOS_Util/plots/res/res_3.gs
  GEOS_Util/plots/tseries/aerosols
  GEOS_Util/plots/zcmp/zcloseplt
  GEOS_Util/plots/zcmp/zplt
  GEOS_Util/plots/zcmp1/progz1
  GEOS_Util/plots/zcmp1/zplt1
  GEOS_Util/post/3CH.F90
  GEOS_Util/post/3CH.j
  GEOS_Util/post/3CH.rc
  GEOS_Util/post/CMakeLists.txt
  GEOS_Util/post/gcmpost.script
  GEOS_Util/post/getdates
  GEOS_Util/post/plot.rc
Labels: 0 diff

#212 Moved lightning files to Chem_Shared
  CHANGELOG.md
  GEOS_Shared/CMakeLists.txt
  GEOS_Shared/Lightning_mod.F90
  GEOS_Shared/lightning_toolbox_mod.F90
Labels: 0 diff

#231 Updated to regrid.pl for gocart2g
  CHANGELOG.md
  GEOS_Util/post/regrid.pl
Labels: enhancement, 0 diff

#236 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial
