Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2021-05, with the labels that each got.

#175 Update main regrid.pl a la #174
  CHANGELOG.md
  GEOS_Util/post/regrid.pl
Labels: 0 diff

#185 Update CircleCI to use large
  .circleci/config.yml
Labels: 0 diff trivial

#168 Updates to use Python2 and Python3 at same time
  .circleci/config.yml
  CHANGELOG.md
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
  GMAO_gfio/CMakeLists.txt
  GMAO_ods/CMakeLists.txt
  GMAO_pyobs/CMakeLists.txt
Labels: 0 diff, 0 diff structural

#184 get it work w/ MAPL2; this still needs a real fix
  CHANGELOG.md
  GMAO_psas/m_GetAI.F90
  GMAO_psas/m_psas.F90
Labels: 0 diff, bug

#186 [skip ci] Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#187 Zero-diff bug fix preventing out-of-bounds error when calculating GEOS-Chem lightning flash rate
  CHANGELOG.md
  GEOS_Shared/Lightning_mod.F90
Labels: 0 diff, bugfix

#188 add ability to write out energy components to file
  GMAO_hermes/m_dyn_util.F90
Labels: 0 diff, 0 diff trivial

#189 Update CHANGELOG.md for release v1.4.2
  CHANGELOG.md
Labels: 0 diff
