Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2021-02, with the labels that each got.

#155 Modifications needed for new mapl generic
  CHANGELOG.md
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/regrid_forcing.F90
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/regrid_forcing_esmf.F90
Labels: 0 diff

#154 Add support for rome node format
  GEOS_Util/coupled_diagnostics/g5lib/plotocn.j
  GEOS_Util/post/gcmplot.script
  GEOS_Util/post/gcmpost.script
  GEOS_Util/post/gcmpost_CPLFCSTfull.script
  GMAO_etc/GMAO_utils.pm
  GMAO_etc/RmShmKeys_sshmpi.csh
Labels: 0 diff trivial

#76 Revised help message for WEMIN in regrid.pl [skip ci]
  GEOS_Util/post/regrid.pl
Labels: 0 diff trivial, documentation

#157 Plot and stats updates from L.Takacs [skip ci]
  CHANGELOG.md
  GEOS_Util/plots/grads_util/make_globl_ctl1
  GEOS_Util/plots/grads_util/pltsys.gs
  GEOS_Util/plots/grads_util/statdplt.gs
  GEOS_Util/plots/grads_util/statmak.gs
  GEOS_Util/plots/grads_util/statmak_sys.gs
  GEOS_Util/plots/moveplot
  GEOS_Util/plots/res/res_3.gs
  GEOS_Util/post/stats.F90
Labels: 0 diff

#158 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#160 Add Python Transition Team Codeowner
  .github/CODEOWNERS
Labels: 0 diff structural, 0 diff trivial, Skip Changelog
