Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2021-11, with the labels that each got.

#223 Closes #94. Update mpi variables in regrid
  CHANGELOG.md
  GEOS_Util/post/regrid.pl
Labels: 0 diff

#224 Add support for GEOS-IT in pyrob
  CHANGELOG.md
  GMAO_etc/pyrob
Labels: enhancement, 0 diff

#225 Update CI to Baselibs 6.2.8
  .circleci/config.yml
  CHANGELOG.md
Labels: 0 diff

#226 Feature/rtodling/cascase
  CHANGELOG.md
  GEOS_Util/post/g5fcst_stats.pl
  GEOS_Util/post/regrid.pl
  GMAO_hermes/dyn_blob.f90
  GMAO_hermes/echorc.f90
Labels: enhancement, 0 diff

#227 Update CHANGELOG.md [skip ci]
  CHANGELOG.md
Labels: 0 diff trivial
