Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2021-06, with the labels that each got.

#191 Update CI image to Baselibs 6.2.4
  .circleci/config.yml
Labels: 0 diff trivial

#190 Feature/rtodling/geo sadas 5 29 0
  CHANGELOG.md
  GEOS_Util/plots/VERIFICATION_RCS/VERIFICATION.ECANA.rc
  GEOS_Util/plots/VERIFICATION_RCS/VERIFICATION.GDAS1.rc
  GEOS_Util/post/g5fcst_stats.pl
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/cube_BCs.pl
  GMAO_etc/obsys-nccs.rc
  GMAO_hermes/dyndot.f90
  GMAO_ods/CMakeLists.txt
  GMAO_ods/diag2ods
  GMAO_ods/m_obs_stats.F90
  GMAO_ods/m_ods.f90
  GMAO_ods/obimp_summary.pl
  GMAO_ods/ods_dcget.f
  GMAO_ods/ods_dconv.f
  GMAO_ods/ods_dcscan.f
  GMAO_ods/ods_diagnc4.f90
  GMAO_ods/odslist.f
  GMAO_ods/odsmatch.rc
  GMAO_ods/odsmeta.h
  GMAO_ods/odsnxtime.f
  GMAO_ods/odsstats.f
  GMAO_ods/ozone-kx.readme
  GMAO_ods/radiance-kx.readme
Labels: 0 diff

#193 [skip ci] Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#197 Fixes some CMake Fortran_MODULE_DIRECTORY
  GEOS_Util/post/CMakeLists.txt
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
Labels: 0 diff structural, Skip Changelog

#196 Adding new script echorc.pl to @GMAO_Shared/GMAO_hermes
  CHANGELOG.md
  GMAO_hermes/CMakeLists.txt
  GMAO_hermes/echorc.pl
Labels: 0 diff

#198 Updates for MVAPICH2
  CHANGELOG.md
  GMAO_etc/esma_mpirun
Labels: 0 diff trivial

#199 minor fix; 181 levs; freq
  GMAO_etc/obsys-nccs.rc
  GMAO_hermes/dyn2dyn.f90
Labels: 0 diff trivial, enhancement

#201 Update changelog enforcer
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
Labels: 0 diff trivial, Skip Changelog

#202 not need to point to other data sources of IASI -MetopC already in OP…
  CHANGELOG.md
  GMAO_etc/obsys-nccs.rc
Labels: Non 0-diff, bugfix
