Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2021-03, with the labels that each got.

#159 Bug fix for issue #99: Edge level arrays out-of-bounds in Lighting_mod
  CHANGELOG.md
  GEOS_Shared/Lightning_mod.F90
Labels: 0 diff

#162 Update binarytile.x for river routing
  CHANGELOG.md
  GEOS_Util/post/binarytile.F90
Labels: 0 diff, enhancement

#164 Remove CMIP_1977_1982 directory
  CHANGELOG.md
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/grads_util/CMIP_ice.ctl
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/grads_util/CMIP_sst.ctl
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/grads_util/plot_CMIP_processed.gs
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/grads_util/yrly_animations/CMIP_ice.ctl
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/grads_util/yrly_animations/CMIP_sst.ctl
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/grads_util/yrly_animations/make_daily_anim.csh
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/grads_util/yrly_animations/plot_CMIP.gs
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/proc_cmip_sst_fraci.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/get_cmip_sst_sic.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/get_ls_mask.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/get_mean_sst_sic.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/get_mean_sst_sic_CLIM.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/compute_mean_clim.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/daily_mean_clim.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/get_cmip_sst_sic.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/grads_utils/cmip_raw_sic.ctl
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/grads_utils/cmip_raw_sst.ctl
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/grads_utils/plot_cmip_raw.gs
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/make_cmip_daily.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_CLIM/sst_sic_monthly_mean.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_cmip_daily.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/make_daily_mean.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/sst_sic_CMIP_mean.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/test_make_ls_mask.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/process_cmip_raw/write_cmip_daily.py
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/read_bin.f90
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMIP_1977_1982/write_cmip_bin.f90
Labels: 0 diff structural

#165 Plot updates for stats from L.Takacs
  CHANGELOG.md
  GEOS_Util/plots/grads_util/corcmpz_plot.gs
  GEOS_Util/plots/grads_util/plot.rc
  GEOS_Util/plots/grads_util/rmscmpz_plot.gs
  GEOS_Util/plots/grads_util/stats
  GEOS_Util/plots/res/zonal.gs
  GEOS_Util/plots/tseries/ps_1
  GEOS_Util/plots/zonal.f
Labels: 0 diff
