Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2022-09, with the labels that each got.

#286 Feature/aelakkra/geosit fix2
  GMAO_etc/obsys-nccs-gaas-geosit.rc
  GMAO_etc/obsys-nccs-gaas-r21c.rc
Labels: 0 diff, bugfix

#279 Feature/jstassi/#278 gmao etc
  CHANGELOG.md
  GMAO_etc/check_obsysrc.py
  GMAO_etc/cmpdir.pl
  GMAO_etc/obsys_rc.py
  GMAO_etc/unittests/outexp/obsys-test1.rc.err
  GMAO_etc/unittests/outexp/obsys-test2.rc.err
  GMAO_etc/unittests/outexp/obsys-test3.rc.err
  GMAO_etc/unittests/outexp/obsys-test4.rc.err
  GMAO_etc/unittests/outexp/obsys-test6.rc.err
  GMAO_etc/unittests/outexp/obsys.rc.test1B.check
  GMAO_etc/unittests/outexp/obsys.rc.test2.check
  GMAO_etc/unittests/outexp/obsys.rc.test3.check
  GMAO_etc/unittests/outexp/obsys.rc.test4.check
  GMAO_etc/unittests/outexp/obsys.rc.test5.check
  GMAO_etc/unittests/outexp/obsys.rc.test6.check
  GMAO_etc/unittests/outexp/obsys.rc.test7.check
  GMAO_etc/unittests/outexp/obsys.rc.test8.check
  GMAO_etc/unittests/test.csh
  GMAO_etc/unittests/test_check_obsysrc.py
Labels: 0 diff

#287 Update CHANGELOG.md to next release
  CHANGELOG.md
Labels: 0 diff trivial

#288 [skip ci] Fix CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#290 Change names for BC, BR, and OC in plots package
  CHANGELOG.md
  GEOS_Util/plots/portrait.script
Labels: 0 diff

#292 [skip ci] Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#294 Plot_Updates_20220915
  CHANGELOG.md
  GEOS_Util/plots/grads_util/cbarn.gs
  GEOS_Util/plots/grads_util/dc.gs
  GEOS_Util/plots/grads_util/lines
  GEOS_Util/plots/grads_util/parea
  GEOS_Util/plots/grads_util/statdplt.gs
  GEOS_Util/plots/grads_util/statdpltz.gs
  GEOS_Util/plots/grads_util/statplt.gs
  GEOS_Util/plots/grads_util/statpltdrv.gs
  GEOS_Util/plots/grads_util/statpltdrvz.gs
  GEOS_Util/plots/grads_util/statpltz.gs
  GEOS_Util/plots/grads_util/vpage
  GEOS_Util/plots/grads_util/writegrads.gs
  GEOS_Util/plots/portrait.script
  GEOS_Util/plots/quickplot
  GEOS_Util/plots/zcmp/progz
  GEOS_Util/plots/zcmp/zplt
Labels: 0 diff
