Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2022-03, with the labels that each got.

#250 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#253 Fix up changelog for 1.5.1
  CHANGELOG.md
Labels: documentation, 0 diff trivial

#245 Support for ocean datasets using ExtData
  .github/CODEOWNERS
  CHANGELOG.md
  GEOS_Util/pre/CMakeLists.txt
  GEOS_Util/pre/prepare_ocnExtData/.gitignore
  GEOS_Util/pre/prepare_ocnExtData/CMakeLists.txt
  GEOS_Util/pre/prepare_ocnExtData/README.md
  GEOS_Util/pre/prepare_ocnExtData/input_template
  GEOS_Util/pre/prepare_ocnExtData/notebooks/.gitignore
  GEOS_Util/pre/prepare_ocnExtData/notebooks/plot_clim_kpar.ipynb
  GEOS_Util/pre/prepare_ocnExtData/notebooks/plot_sst_ice.ipynb
  GEOS_Util/pre/prepare_ocnExtData/ocnExtData_utils.py
  GEOS_Util/pre/prepare_ocnExtData/plot_binary_sst_ice.py
  GEOS_Util/pre/prepare_ocnExtData/plot_sst_ice.py
  GEOS_Util/pre/prepare_ocnExtData/proc_SST_FRACI_eight.F90
  GEOS_Util/pre/prepare_ocnExtData/read_sst_ice_bin.f90
  GEOS_Util/pre/prepare_ocnExtData/sst_ice_helpers.F90
  GEOS_Util/pre/prepare_ocnExtData/write_kPAR.py
Labels: documentation, enhancement, 0 diff trivial

#251 Bugfix/jstassi/#247 manipulate time.pm
  CHANGELOG.md
  GMAO_etc/Manipulate_time.pm
  GMAO_etc/obsys-nccs.rc
Labels: 0 diff, bugfix

#254 Updates to support Spack
  CHANGELOG.md
  GEOS_Shared/CMakeLists.txt
  GEOS_Util/post/CMakeLists.txt
  GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
  GEOS_Util/pre/prepare_ocnExtData/CMakeLists.txt
  GMAO_etc/CMakeLists.txt
  GMAO_gfio/CMakeLists.txt
  GMAO_stoch/CMakeLists.txt
Labels: 0 diff

#252 chckhist.new update to fix plotting for OPS HISTORY.rc, minor 3CH bug…
  CHANGELOG.md
  GEOS_Util/plots/chckhist.new
  GEOS_Util/post/3CH.F90
  GEOS_Util/post/3CH.j
Labels: 0 diff, bugfix

#257 Update tags in regrid.pl. Fix up changelog
  CHANGELOG.md
  GEOS_Util/post/regrid.pl
Labels: 0 diff
