Repository GEOS-ESM/GMAO_Shared, pull requests merged in 2025-08, with the labels that each got.

#391 Feature/jstassi/#390 cmpdir ignore diffs
  GMAO_etc/cmpdir.pl
Labels: 0 diff trivial, Skip Changelog

#388 Update openmpi in esma_mpirun
  CHANGELOG.md
  GMAO_etc/esma_mpirun
Labels: 0 diff

#392 [skip_ci] Uptick to v2.14
  CHANGELOG.md
Labels: 0 diff, 0 diff trivial
